---
- hosts: app
  become: true
  tasks:
    - name: install web componants
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - apache2
        - php
        - libapache2-mod-php 
        - php-mcrypt
        - php-mysql
    
    - name: remove html
      file: path='/var/www/html/index.html' state=absent
  

    - name: get github repo
      copy: src=it635/ dest=/var/www/ mode=0755
      notify: restart apache2

              
      notify: restart apache2
 
    - name: ensure apache2 is running
      service: name=apache2 state=started enabled=yes

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted



