---
# Bring stack down
- hosts: lb
  become: true
  tasks:
    - service: name=nginx state=stopped
    - wait_for: port=80 state=drained

- hosts: app
  become: true
  tasks:
    - service: name=apache2 state=stopped
    - wait_for: port=80 state=stopped

# Restart mysql
- hosts: database
  become: true
  tasks:
    - service: name=mysql state=restarted
    - wait_for: port=3306 state=started

# Bring stack up
- hosts: app
  become: true
  tasks:
    - service: name=apache2 state=started
    - wait_for: port=80

- hosts: lb
  become: true
  tasks:
    - service: name=nginx state=started
    - wait_for: port=80
