---
- hosts: app
  become: true
  tasks:
    - name: install web componants
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - apache2
        - php
        - libapache2-mod-php 
        - php-mcrypt
        - php-mysql


    - name: get github repo
      command: git clone -b final https://github.com/shivamXP/it635.git
               cp /it635/*  /var/www/
               
              
      notify: restart apache2
 
    - name: ensure apache2 is running
      service: name=apache2 state=started enabled=yes

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted



